#ifndef TIMEFUNCDLL_SERVICE_H
#define TIMEFUNCDLL_SERVICE_H

#include <stdio.h>



// Time Conversion Functions
// CONVERT DAYS SINCE 1950 TO YYYY/DDD HHMM SS.SSS
char* UTCToDtg20Str(double ds50UTC);


// CONVERT DAYS SINCE 1950 TO YYYYMonDDHHMMSS.SSS
char* UTCToDtg19Str(double ds50UTC);

// CONVERT DAYS SINCE 1950 TO YY/DDD HHMM SS.SSS
char* UTCToDtg18Str(double ds50UTC);

// CONVERT DAYS SINCE 1950 TO YYYY/DDD.DDDDDDDD
char* UTCToDtg17Str(double ds50UTC);


// CONVERT DAYS SINCE 1950 TO 'YYDDDHHMMSS.SSS'
char* UTCToDtg15Str(double ds50UTC);

// CONVERT DAYS SINCE 1950 TO 'YY DDD HH MM SS.SSSSSSS'
char* UTCToDtg23Str(double ds50UTC);

// CONVERT DAYS SINCE 1950 TO 'YY DDD HH MM SS.SSS'
char* UTCToDtg19aStr(double ds50UTC);

// CONVERT DAYS SINCE 1950 TO 'YYYYDDDHHMMSS.SSS'
char* UTCToYYYYDDDHHMMSSsssStr(double ds50UTC);



#endif
